### ISSUE TITLE
Python quickstarts Test/Checks fail (Config API get result)

### ISSUE THREAD

**Issue by paulyuk** [dapr/quickstarts#1050]
## Expected Behavior
Python tests pass.  LKG in main is:
[Valid result with Dapr 1.13.0](https://github.com/dapr/quickstarts/actions/runs/9702023200)

## Actual Behavior

Using Dapr 1.13.5 and no other changes, I see this new failures on the return of Config API

[Failure result with Dapr 1.13.5](https://github.com/dapr/quickstarts/actions/runs/9849541177/job/27193373380?pr=1049#step:14:2891)

**Comment by paulyuk** [comment]
@berndverst any ideas?

**Comment by berndverst** [comment]
Two things: you aren't version pinning - so this pulled in either the latest -dev image or the pre lease 1.14 RC1.

Secondly, this is by design - I fixed an a customer reported typing issue where config API had not returned the expected type. You will want to call the ".json()" method on each returned configuration item.

**Comment by berndverst** [comment]
See Python SDK folder, example for config API

**Comment by berndverst** [comment]
https://github.com/dapr/python-sdk/issues/720

**Comment by paulyuk** [comment]
Fix avail ^^

**Comment by paulyuk** [comment]
fixed by #1051
