### ISSUE TITLE
Documentation errors in hello-kubernetes quickstart

### ISSUE THREAD

**Issue by yoDon** [dapr/quickstarts#367]
## Expected Behavior

hello-kubernetes quickstart should run without error

## Actual Behavior

There are multiple errors in [Step 3 - Deploy the Node.js app with the Dapr sidecar](https://github.com/dapr/quickstarts/tree/v1.0.0-rc.2/hello-kubernetes#step-3---deploy-the-nodejs-app-with-the-dapr-sidecar).

Note: I am running in kubernetes under Docker Desktop for Windows. Some or all of the following errors will also be present when running kubernetes via minikube and/or under Linux or OSX.

- The windows steps for setting the `$NODE_APP` environment variable show a DOS Command Prompt line with three single quotes. This can't be a valid command, and as a result it fails to run.
- The Linux, OSX, and Windows commands for setting the `NODE_APP` environment variable reference a json property that does not exist. They are looking for `jsonpath={.status.loadBalancer.ingress[0].ip}` which the json will not contain for users who have followed the default dapr install directions and quickstart instructions. The correct property to use is `jsonpath={.status.loadBalancer.ingress[0].hostname}` (this error is related to https://github.com/dapr/quickstarts/issues/355) 
- Even when the single quotes and property name are fixed in the Windows example, the syntax of the DOS Command Prompt used for setting the environment variable is invalid and generates an error rather than than setting an environment variable
- Given that most modern Microsoft instructions use PowerShell rather than old-school DOS Command Prompt syntax, rather than trying to figure out what is wrong with the DOS line I recommend replacing it with the following PowerShell, which is much simpler and which works as expected `$NODE_APP=(kubectl get svc nodeapp --output 'jsonpath={.status.loadBalancer.ingress[0].hostname}')`

## Steps to Reproduce the Problem

See above

**Comment by wcs1only** [comment]
I believe we've captured everything you've mentioned here between:

#415
#431

and possibly a few others.

- We largely removed the setting of environment variables, and single quote/double quotes to avoid having different steps for bash/CMD/powershell. 
- We've opted for port forwarding over querying for the service IP address/port, since port forwarding is more consistent across kubernetes implementations. This allows us to use a fix localhost/port combination and should be far more cross platform.
- We've added Windows support to our quickstart automated validation, so that Windows/Linux/MacOS do not drift apart as changes are made.

Thanks for your detailed feedback. I'm going to go ahead and close up this issue. If you have any further trouble with the quickstarts on Windows, please open a new issue, or drop in our community discord: https://aka.ms/dapr-discord
