### ISSUE TITLE
PubSub with RabbitMQ 

### ISSUE THREAD

**Issue by kamesh1677** [dapr/quickstarts#408]
Hi Team,

I am trying quick start example for PubSub provided in Quickstart Repo with RabbitMQ.I am able to publish and subscribe messages.

My Question is  , The exchange is created with name what ever provided in the node application as "A" in the RabbitMQ UI. where as the Queue name is appended with {appid}-{queueName} (node-subscriber-A) . How to provide queue name as User specific . Example (queueA).

**Comment by yaoliu** [comment]
QueueName cannot be customized at this time
now: queueName := fmt.Sprintf("%s-%s", r.metadata.consumerID, req.Topic)

**Comment by wcs1only** [comment]
When using PUB/SUB, queue names are managed by daprd, so that both the publish and subscriber can be ensured to be using the same naming convention. If you want a little more flexibility, you can use the rabbitmq binding, which will allow you to manage queue names yourself:

https://docs.dapr.io/reference/components-reference/supported-bindings/rabbitmq/
