### ISSUE TITLE
Failed to create nodeapp according the sample of the hello-kubernetes.

### ISSUE THREAD

**Issue by kinderyj** [dapr/quickstarts#419]
kubectl get pod
NAME                                 READY   STATUS             RESTARTS   AGE
nodeapp-5dd5d64c5c-xsf6c             1/2     CrashLoopBackOff   9          21m
redis-master-0                       1/1     Running            0          140m
redis-slave-0                        1/1     Running            0          140m
redis-slave-1                        1/1     Running            0          132m

kubectl get svc
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                               AGE
kubernetes       ClusterIP      192.168.0.1     <none>           443/TCP                               6d1h
nodeapp          LoadBalancer   192.168.91.19   175.27.192.113   80:30651/TCP                          53m
nodeapp-dapr     ClusterIP      None            <none>           80/TCP,50001/TCP,50002/TCP,9090/TCP   53m
redis-headless   ClusterIP      None            <none>           6379/TCP                              140m
redis-master     ClusterIP      192.168.2.218   <none>           6379/TCP                              140m
redis-slave      ClusterIP      192.168.19.63   <none>           6379/TCP                              140m

kubectl get component statestore -oyaml
apiVersion: dapr.io/v1alpha1
auth:
  secretStore: kubernetes
kind: Component
metadata:
  creationTimestamp: "2021-04-13T03:04:17Z"
  generation: 1
  name: statestore
  namespace: default
  resourceVersion: "7231248802"
  selfLink: /apis/dapr.io/v1alpha1/namespaces/default/components/statestore
  uid: e492f2e6-be23-477f-a0a9-59c64c024b3d
spec:
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      key: is07YbzBtU
      name: redis
  type: state.redis
  version: v1

export REDIS_PASSWORD=$(kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 --decode)
➜  ~ echo $REDIS_PASSWORD
is07YbzBtU

## Actual Behavior

kubectl logs nodeapp-5dd5d64c5c-xsf6c daprd
msg="process component statestore error: redis store: error connecting to redis at redis-master:6379: NOAUTH Authentication required." app_id=nodeapp instance=nodeapp-5dd5d64c5c-xsf6c scope=dapr.runtime type=log ver=1.1.1

**Comment by wcs1only** [comment]
Ok, if you are using helm to install redis, you don't need to modify redis.yaml at all. See the note on step 2 here: https://github.com/dapr/quickstarts/blob/master/hello-kubernetes/README.md#step-2---create-and-configure-a-state-store

The password will be read from the kubernetes secret store, and thus not stored in plaintext in your configuration. This is the most secure behavior and will prevent leaking of the key when viewing configuration. If you do want to store the key in plaintext, you'll need to store the key as a value, rather than as a secretKeyRef. For more information see:
https://docs.dapr.io/operations/components/component-secrets/

**Comment by wcs1only** [comment]
Also, be sure you remove this redis installation and key since you have shared the secret in a public github issue.
