### ISSUE TITLE
pub-sub:   File app.py, SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by AtticusYang** [dapr/quickstarts#488]
## Expected Behavior

python3, python app.py give the above error

File "app.py", line 22
    print(f'A: {request.json}', flush=True)
                             ^
SyntaxError: invalid syntax

**Comment by wcs1only** [comment]
What version of python are you using?

**Comment by wcs1only** [comment]
I'm afraid we're going to need more details for this issue to be actionable. We have automated validation of our quickstarts, and they are currently passing for the python example apps:

https://github.com/dapr/quickstarts/runs/4230761201?check_suite_focus=true#step:16:240

In order to address your issue, we'll need:
- Python version
- Which quickstart isn't working
- What OS/environment are you running it on.
- Any other details you can provide that can help us reproduce what you are seeing.

**Comment by wcs1only** [comment]
We haven't had any feedback on this issue for 2+ months. Closing. If you are still experiencing issues, please open a new issue, or head over to our community discord:

https://aka.ms/dapr-discord
