### ISSUE TITLE
can't run hello-world in dev container

### ISSUE THREAD

**Issue by spottedmahn** [dapr/quickstarts#499]
## Expected Behavior

I can debug the node hello-world app in a dev container

## Actual Behavior

>Error: A compatible version of Dapr has not been initialized. You may need to install a more recent version.

## Steps to Reproduce the Problem

1. clone repo in wsl
2. `cd quickstarts`
2. `code-insiders .`
3. update dev container image to 1.6.9, reference: [Rvm default gid conflicts with user gid syncing](https://github.com/microsoft/vscode-dev-containers/issues/1192#issuecomment-985842053)
3. say yes when prompting if you want to open a dev container
4. open the `hello-world` folder
5. run debugger on node app

![image](https://user-images.githubusercontent.com/14079228/144889949-97b8f06b-2f35-4f99-a05d-a8df5990d321.png)

![image](https://user-images.githubusercontent.com/14079228/144889988-34333653-3747-46c2-a75a-a41c1811d5fb.png)

![image](https://user-images.githubusercontent.com/14079228/144890138-fa59eceb-49b0-4470-b04f-c99cfcaff17f.png)

---

![image](https://user-images.githubusercontent.com/14079228/144890042-11c00ddb-5ddf-4897-82b9-d0d6e137bc4f.png)

![image](https://user-images.githubusercontent.com/14079228/144890307-c40539c0-bf95-457d-9aad-eeadf774cc39.png)

**Comment by wcs1only** [comment]
This is a good case for resurrecting #448

**Comment by paulyuk** [comment]
Hey @spottedmahn - sorry about this.  we need to dig into why.  I can see that daprd is not by default where it's expected.  this looks like an incomplete install from dockerfile.

To workaround for now you can do this from the VS-Code Terminal:
`dapr uninstall --all`
`dapr init`

You should no longer see the dapr_placement container already exists because the uninstall step cleaned that up.  then you should be able to do this with success:

`dapr run --app-id nodeapp --app-port 3000 --dapr-http-port 3500 node app.js`

**Comment by paulyuk** [comment]
@spottedmahn any chance you want to test and approve the PR I have above?

**Comment by paulyuk** [comment]
I believe this is fixed, but please reopen if not
